#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

"""Apply photo-inspired Linker Hand L10 colors to the generated combined URDF."""

from __future__ import annotations

import argparse
import xml.etree.ElementTree as ET
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_URDF = REPO_ROOT / "assets" / "generated" / "dual_nero_linker_l10_combined.urdf"
GENERATED_COMMENT = "Generated by tools/build_add_scene_combined_urdf.py from add_scene_glb.py assembly constants."

COLORS = {
    "outer_shell": ("right_l10_warm_light_grey", "0.70 0.72 0.70 1"),
    "silver_link": ("right_l10_satin_silver", "0.78 0.80 0.78 1"),
    "medium_joint": ("right_l10_medium_grey", "0.46 0.48 0.47 1"),
    "rubber": ("right_l10_rubber_dark_grey", "0.16 0.17 0.17 1"),
}
OLD_PAD_MATERIAL = "right_l10_black_rubber_pad"

LINK_COLOR_KEYS = {
    "right_l10_hand_base_link": "outer_shell",
    "right_l10_thumb_metacarpals_base1": "silver_link",
    "right_l10_thumb_metacarpals_base2": "outer_shell",
    "right_l10_thumb_metacarpals": "silver_link",
    "right_l10_thumb_proximal": "medium_joint",
    "right_l10_thumb_distal": "rubber",
    "right_l10_index_metacarpals": "silver_link",
    "right_l10_index_proximal": "medium_joint",
    "right_l10_index_middle": "rubber",
    "right_l10_index_distal": "rubber",
    "right_l10_middle_proximal": "medium_joint",
    "right_l10_middle_middle": "rubber",
    "right_l10_middle_distal": "rubber",
    "right_l10_ring_metacarpals": "silver_link",
    "right_l10_ring_proximal": "medium_joint",
    "right_l10_ring_middle": "rubber",
    "right_l10_ring_distal": "rubber",
    "right_l10_pinky_metacarpals": "silver_link",
    "right_l10_pinky_proximal": "medium_joint",
    "right_l10_pinky_middle": "rubber",
    "right_l10_pinky_distal": "rubber",
}


def _set_visual_material(visual: ET.Element, material_name: str, rgba: str) -> None:
    material = visual.find("material")
    if material is None:
        material = ET.SubElement(visual, "material")
    material.set("name", material_name)
    color = material.find("color")
    if color is None:
        color = ET.SubElement(material, "color")
    color.set("rgba", rgba)


def apply_colors(urdf_path: Path) -> None:
    tree = ET.parse(urdf_path)
    root = tree.getroot()
    if not any(child.tag is ET.Comment and child.text == GENERATED_COMMENT for child in root):
        root.insert(0, ET.Comment(GENERATED_COMMENT))

    changed_links = 0
    for link in root.findall("link"):
        link_name = link.get("name", "")
        color_key = LINK_COLOR_KEYS.get(link_name)
        if color_key is None:
            continue
        visual = link.find("visual")
        if visual is None:
            continue
        _set_visual_material(visual, *COLORS[color_key])
        changed_links += 1

    hand_base = root.find("./link[@name='right_l10_hand_base_link']")
    if hand_base is None:
        raise RuntimeError("Missing right_l10_hand_base_link in URDF")
    old_pads = [
        visual
        for visual in hand_base.findall("visual")
        if visual.find("material") is not None
        and visual.find("material").get("name") == OLD_PAD_MATERIAL
    ]
    for visual in old_pads:
        hand_base.remove(visual)

    if changed_links != len(LINK_COLOR_KEYS):
        raise RuntimeError(f"Colored {changed_links} L10 links, expected {len(LINK_COLOR_KEYS)}")

    ET.indent(tree, space="  ")
    tree.write(urdf_path, encoding="utf-8", xml_declaration=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", type=Path, default=DEFAULT_URDF)
    args = parser.parse_args()
    apply_colors(args.urdf.resolve())
    print(f"Applied L10 photo colors: {args.urdf}")


if __name__ == "__main__":
    main()
