from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
for import_root in (REPO_ROOT, REPO_ROOT / "src"):
    if str(import_root) not in sys.path:
        sys.path.insert(0, str(import_root))

from teleop_stack.paths import resolve_isaac_teleop_root

ARCH_START_MARKER = "# Pick the right base image per architecture.\n"
ARCH_END_MARKER = "# Runs as root: the container requires privileged access to USB cameras (ZED,\n"
ZED_START_MARKER = "############################################################\n# ZED SDK (architecture-dependent)\n############################################################\n\n"
ZED_END_MARKER = "############################################################\n# Python Dependencies\n############################################################\n\n"
ENTRYPOINT_START_MARKER = "COPY --chmod=755 <<'ENTRY' /usr/local/bin/camera-sender-entrypoint\n"
ENTRYPOINT_END_MARKER = "ENTRY\n"
SYSTEM_DEPS_MARKER = "    libxcb-glx0-dev \\\n"


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a patched camera_streamer Dockerfile for RealSense-only/V4L2-only bring-up.",
    )
    parser.add_argument(
        "--upstream-dockerfile",
        type=Path,
        default=None,
        help="Optional path to the upstream camera_streamer Dockerfile.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output Dockerfile path.",
    )
    parser.add_argument(
        "--base-image",
        required=True,
        help="Single-architecture Holoscan base image to use in the patched Dockerfile.",
    )
    parser.add_argument(
        "--target-arch",
        required=True,
        choices=["amd64", "arm64"],
        help="Resolved host architecture for the patched Dockerfile.",
    )
    parser.add_argument(
        "--skip-zed",
        action="store_true",
        help="Remove the unconditional ZED SDK install block.",
    )
    return parser


def _default_upstream_dockerfile() -> Path:
    isaac_teleop_root = resolve_isaac_teleop_root()
    return isaac_teleop_root / "examples" / "camera_streamer" / "Dockerfile"


def _replace_arch_block(source: str, *, base_image: str, target_arch: str) -> str:
    start = source.find(ARCH_START_MARKER)
    end = source.find(ARCH_END_MARKER)
    if start == -1 or end == -1 or end <= start:
        raise RuntimeError("Failed to locate architecture selection block in upstream Dockerfile.")

    replacement = (
        ARCH_START_MARKER + f"ARG BASE_IMG={base_image}\n\n"
        "############################################################\n"
        "# Host-architecture base target generated by teleop_stack\n"
        "############################################################\n"
        "FROM ${BASE_IMG} AS base\n\n"
        f"ARG TARGETARCH={target_arch}\n\n"
    )
    return source[:start] + replacement + source[end:]


def _replace_zed_block(source: str) -> str:
    start = source.find(ZED_START_MARKER)
    end = source.find(ZED_END_MARKER)
    if start == -1 or end == -1 or end <= start:
        raise RuntimeError("Failed to locate ZED SDK block in upstream Dockerfile.")

    replacement = (
        "############################################################\n"
        "# ZED SDK intentionally omitted by teleop_stack RealSense-only build\n"
        "############################################################\n\n"
        'RUN echo "[teleop_stack] skipping ZED SDK install for RealSense-only/V4L2-only image"\n\n' + ZED_END_MARKER
    )
    return source[:start] + replacement + source[end + len(ZED_END_MARKER) :]


def _ensure_xr_system_dependencies(source: str) -> str:
    if "libvulkan-dev" in source:
        return source
    if SYSTEM_DEPS_MARKER not in source:
        raise RuntimeError("Failed to locate system dependency block in upstream Dockerfile.")
    return source.replace(
        SYSTEM_DEPS_MARKER,
        SYSTEM_DEPS_MARKER + "    libvulkan-dev \\\n",
        1,
    )


def _replace_entrypoint_heredoc(source: str) -> str:
    start = source.find(ENTRYPOINT_START_MARKER)
    if start == -1:
        raise RuntimeError("Failed to locate entrypoint heredoc block in upstream Dockerfile.")

    content_start = start + len(ENTRYPOINT_START_MARKER)
    end = source.find(ENTRYPOINT_END_MARKER, content_start)
    if end == -1 or end <= content_start:
        raise RuntimeError("Failed to locate entrypoint heredoc terminator in upstream Dockerfile.")

    script_body = source[content_start:end]
    script_lines = script_body.splitlines()
    if not script_lines:
        raise RuntimeError("Entrypoint script body is empty in upstream Dockerfile.")

    def _shell_single_quote(line: str) -> str:
        return "'" + line.replace("'", "'\"'\"'") + "'"

    printf_args = " \\\n".join(f"    {_shell_single_quote(line)}" for line in script_lines)
    replacement = (
        "RUN printf '%s\\n' \\\n"
        + printf_args
        + " \\\n"
        + "    > /usr/local/bin/camera-sender-entrypoint \\\n"
        + "    && chmod 755 /usr/local/bin/camera-sender-entrypoint\n"
    )
    return source[:start] + replacement + source[end + len(ENTRYPOINT_END_MARKER) :]


def main() -> int:
    args = _build_parser().parse_args()
    upstream_dockerfile = (
        args.upstream_dockerfile.resolve() if args.upstream_dockerfile is not None else _default_upstream_dockerfile()
    )
    source = upstream_dockerfile.read_text(encoding="utf-8")
    patched = _replace_arch_block(
        source,
        base_image=args.base_image,
        target_arch=args.target_arch,
    )
    patched = _ensure_xr_system_dependencies(patched)
    if args.skip_zed:
        patched = _replace_zed_block(patched)
    patched = _replace_entrypoint_heredoc(patched)

    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(patched, encoding="utf-8")
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
